### ISSUE TITLE
Tail type gives wrong results in specific recursive scenarios

### ISSUE THREAD

**Issue by TimonLukas** [webNeat/just-types#1]
Hey there! Pretty cool library, thanks for sharing this. I could have recently needed this, it's good to know it exists! Though one tip, it would be helpful to add a link to the repository in your `package.json`, so the Github repository is linked on NPM :)

Anyways, here's the issue. There are some situations in which the `Tail` type will not work correctly, like this one ([see on TS playground](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAKghgSwDYB4AyCDOwoQB7AQB2AJplHESANoC6AfFALxQba4HFlTUJEBmEAE5QA+gBooAOhl9BIgEoRstAFBQoAfihLs6qAC4ea1aEixESAEwoAkkTABXHPkKlylGg2ZQAFL5kpOCEAc0wjeydgAEpmRk9Y1y5yX31gkKNPcX1AoWVgIzlhHXzVWKZ4qn1tXWB9IyIIADdhVVNwaABZOGAAYwALAFE4AYxGlBgON25sIT4QukYWSaT3Hn1+iDgSI1n57I1A4Etd4DmiBbU1DW1uvqGR-rGICcsJ+np6qEaWoVUgA)):

```typescript
type Tail<List extends any[]> = List extends [infer _, ...infer Rest] ? Rest : []

type MatchEachLine<T extends string[]> =
  T extends [ head: string, ...tail: string[] ]
  ? MatchEachLine<Tail<T>>
  : never
```

This makes TS throw an error:

```
TS2344: Type 'Tail<T>' does not satisfy the constraint 'string[]'.
   Type 'unknown[] | []' is not assignable to type 'string[]'.
     Type 'unknown[]' is not assignable to type 'string[]'.
       Type 'unknown[]' is not assignable to type 'string[]'.
         Type 'unknown' is not assignable to type 'string'.
```

This should work, but TS somehow doesn't like this. Don't ask me why, hopefully it will be fixed in the future...

However, there is an alternative that fixes this and still fulfills all your existing tests ([see on TS playground](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAkgzgHgCpQgD2BAdgEzlYAJwFcIA+KAXiiQChRIoBRAR2IEMAbBADQBooATQrUmaAMadiOCLwHCoAH2YSpMhIIE8K6TLnxYIANwiEoAfgIloALigAzLnAi164aEnYBLTgEYEADJecMCoGNh4UOxYIADaALoiUEEhYXqRsV5Y9qZQAPoCAHTFWTlmAEoQIfEWUJWpdglujJ4+AEwIMFhgxKG6EfjRcYlUUAAUY8WF7IQA5nB2XT3AAJRUFENr-frjM7N2Q0XFhFXAdqW59avrUTG1V1B2hiaErgwe3two25FDCUmtTgdJBkN7uKAAWXYwHEAAsmOw4UFDMg0gMoCFCFlZv8qLQoDQ0TtYlBYRB2Dg7JjsUdCsBPlSiNiElB4vjalCYfDEbDkbJAcgyKCCU9jKYwS1TvhqLF2fAEKwOF9Pgh-gJ-mQ+HLEIquMgVbEAOTsQ2JdWJTXahVsPUCo0mgSGgBGps1UCNLotWoJ8t1yp8quNhsdLsd4mDUENOFd6udEcN4cd0YttHiQA)):

```typescript
type Tail<List extends any[]> = ((...args: List) => any) extends (arg: any, ...rest: infer Rest) => any ? Rest : never
```

**Comment by webNeat** [comment]
Hey @TimonLukas

Thank you for opening this issue and giving the solution, I am not sure why TS behave that way, I will try to dig deeper and understand where is this error coming from later. For now I applied your solution and released a new version.

Also thanks for the tip about the `repository` on `package.json`, I totally missed that :sweat_smile: 

Feel free to open other issues if you found other bugs.
